sephp.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/sephp.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/sephp.c -o sephp.lo 
kernel/main.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/main.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/main.c -o kernel/main.lo 
kernel/memory.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/memory.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/memory.c -o kernel/memory.lo 
kernel/exception.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/exception.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/exception.c -o kernel/exception.lo 
kernel/debug.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/debug.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/debug.c -o kernel/debug.lo 
kernel/backtrace.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/backtrace.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/backtrace.c -o kernel/backtrace.lo 
kernel/object.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/object.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/object.c -o kernel/object.lo 
kernel/array.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/array.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/array.c -o kernel/array.lo 
kernel/string.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/string.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/string.c -o kernel/string.lo 
kernel/fcall.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/fcall.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/fcall.c -o kernel/fcall.lo 
kernel/require.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/require.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/require.c -o kernel/require.lo 
kernel/file.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/file.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/file.c -o kernel/file.lo 
kernel/operators.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/operators.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/operators.c -o kernel/operators.lo 
kernel/math.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/math.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/math.c -o kernel/math.lo 
kernel/concat.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/concat.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/concat.c -o kernel/concat.lo 
kernel/variables.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/variables.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/variables.c -o kernel/variables.lo 
kernel/filter.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/filter.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/filter.c -o kernel/filter.lo 
kernel/iterator.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/iterator.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/iterator.c -o kernel/iterator.lo 
kernel/time.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/time.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/time.c -o kernel/time.lo 
kernel/exit.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/exit.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/kernel/exit.c -o kernel/exit.lo 
sephp/seframework.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/sephp/seframework.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/sephp/seframework.zep.c -o sephp/seframework.lo 
sephp/view.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/sephp/view.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/sephp/view.zep.c -o sephp/view.lo 
sephp/common/rsa.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/sephp/common/rsa.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/sephp/common/rsa.zep.c -o sephp/common/rsa.lo 
sephp/common/utils.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/sephp/common/utils.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/sephp/common/utils.zep.c -o sephp/common/utils.lo 
sephp/0__closure.lo: /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/sephp/0__closure.zep.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/xiangjiwu/PhpstormProjects/zp/sephp/ext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/xiangjiwu/PhpstormProjects/zp/sephp/ext/sephp/0__closure.zep.c -o sephp/0__closure.lo 
$(phplibdir)/sephp.la: ./sephp.la
	$(LIBTOOL) --mode=install cp ./sephp.la $(phplibdir)

./sephp.la: $(shared_objects_sephp) $(SEPHP_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_sephp) $(SEPHP_SHARED_LIBADD)

